apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup-azure
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-backup-azure
              image: dazlabteam/postgres-backup-azure
              envFrom:
                - secretRef:
                  name: postgres-backup-azure
          restartPolicy: Never
